package com.ezen.lolketing.util

object Constants {
    const val USERS = "Users"
    const val TEAM = "team"
    const val BOARD = "Board"
    const val COMMENTS = "Comments"
    const val SHOP = "Shop"
    const val GAME = "Game"
    const val SEAT = "Seat"
    const val DATE = "date"
    const val COUPON = "Coupon"
    const val PURCHASE = "Purchase"
    const val TeamCollection = "Team"
    const val PLAYER = "Player"
    const val TIME = "time"
    const val ID = "id"
    const val Email = "email"
    const val DOCUMENT_ID = "documentId"
    const val SELECT_IMAGE = "select_image"
    const val GALLERY_LIST = "Gallery List"
    const val POSITION = "position"
    const val URL = "url"
    const val TITLE = "title"
    const val NICKNAME = "nickname"
    const val ADDRESS_API_BASE_URL = "https://www.juso.go.kr/"
    const val NAVER_API_BASE_URL = "https://openapi.naver.com/v1/"
}